/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EX3;

/**
 *
 * @author LENOVO
 */
import java.awt.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;

public class secondfont extends javax.swing.JFrame {
    firstfont f1;
    String text;
    Font font;
    Color textc;
    Color backgroundc;
    /**
     * Creates new form secondfont
     */
    public secondfont() {
        initComponents();
    }

    public secondfont(EX3.firstfont f1, String text, Font f, Color textColor, Color bgColor) {
        initComponents();
        this.f1 = f1;
        this.text = text;
        font = f;
        this.textc = textColor;
        backgroundc = bgColor;
        lblDisplay.setText(text);
        lblDisplay.setFont(font);
        lblDisplay.setForeground(textc);
        lblDisplay.setBackground(bgColor);
        LoadFontName();
        LoadFontStyle();
    }
    
     private void LoadFontName(){
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] fortName = ge.getAvailableFontFamilyNames();
        lstFontname.setModel(new DefaultComboBoxModel<String>(fortName));
    }
    
    private void LoadFontStyle(){
        String[] fortStyle = {"Regular", "Italic", "Bold", "Bold & Italic"};
        lstFontstyle.setModel(new DefaultComboBoxModel<String>(fortStyle));
    }
    
    private void Format(){
        String FonName = lstFontname.getSelectedIndex()+"";
        int FonStyle = lstFontstyle.getSelectedIndex();
        int FonSize = 0;
        try {
            FonSize = Integer.parseInt(txtFontsize.getText());
            FonSize = FonSize>50?50:FonSize;
            FonSize = FonSize<10?10:FonSize;
        } catch (Exception e){
            FonSize = 15;
        }
        lblDisplay.setFont(new Font(FonName, FonStyle, FonSize));
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisplay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFontname = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFontstyle = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txtFontsize = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnTextcolor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnBackgroundcolor = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Font Name");

        lstFontname.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstFontname.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstFontnameValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstFontname);

        jLabel2.setText("Font Style");

        lstFontstyle.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstFontstyle.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstFontstyleValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstFontstyle);

        jLabel3.setText("Font Size");

        txtFontsize.setText("15");
        txtFontsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFontsizeActionPerformed(evt);
            }
        });

        jLabel4.setText("Text Color");

        btnTextcolor.setText("Chang Text color...");
        btnTextcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTextcolorActionPerformed(evt);
            }
        });

        jLabel5.setText("Background Color");

        btnBackgroundcolor.setText("Chang Background color...");
        btnBackgroundcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackgroundcolorActionPerformed(evt);
            }
        });

        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFontsize, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTextcolor)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBackgroundcolor)
                            .addComponent(jLabel5))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinish)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(txtFontsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTextcolor)
                    .addComponent(btnBackgroundcolor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnFinish)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstFontnameValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFontnameValueChanged
        // TODO add your handling code here:
        Format();
    }//GEN-LAST:event_lstFontnameValueChanged

    private void lstFontstyleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFontstyleValueChanged
        // TODO add your handling code here:
        Format();
    }//GEN-LAST:event_lstFontstyleValueChanged

    private void txtFontsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFontsizeActionPerformed
        // TODO add your handling code here:
        Format();
    }//GEN-LAST:event_txtFontsizeActionPerformed

    private void btnTextcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextcolorActionPerformed
        // TODO add your handling code here:
        textc = JColorChooser.showDialog(this, "Select color for text", textc);
        Format();
    }//GEN-LAST:event_btnTextcolorActionPerformed

    private void btnBackgroundcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackgroundcolorActionPerformed
        // TODO add your handling code here:
        backgroundc = JColorChooser.showDialog(this, "Select color for background", backgroundc);
        Format();
    }//GEN-LAST:event_btnBackgroundcolorActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
        f1.Format(font, textc, backgroundc);
        this.dispose();
    }//GEN-LAST:event_btnFinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(secondfont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(secondfont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(secondfont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(secondfont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secondfont().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackgroundcolor;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnTextcolor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JList<String> lstFontname;
    private javax.swing.JList<String> lstFontstyle;
    private javax.swing.JTextField txtFontsize;
    // End of variables declaration//GEN-END:variables
}
