package Ex1;

import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PH
 */
public class Ex5 extends javax.swing.JFrame {

    /**
     * Creates new form Ex5
     */
    public Ex5() {
        initComponents();
        initThread();
    }

    String s = "";
    Thread t;
    boolean CanRun = false;

    private void initThread() {
        t = new Thread() {
            @Override
            public void run() {
                while (true) {
                    if (CanRun) {
//
                        if (cbxChar.isSelected()) {
                            if (cbxRight.isSelected()) {
                                s = MoveChar(s, true);
                            } else if (cbxLeft.isSelected()) {
                                s = MoveChar(s, false);
                            }
                        } else if (cbxWord.isSelected()) {
                            if (cbxRight.isSelected()) {
                                s = MoveWord(s, true);
                            } else if (cbxLeft.isSelected()) {
                                s = MoveWord(s, false);
                            }
                        }
                        lblDisplay.setText(s);

                    }
                    try {
                        Thread.sleep((int) sldSpeed.getValue());
                    } catch (Exception e) {
                    }
                }
            }

        };
        t.start();
    }

    private String MoveChar(String s, boolean direct) {
        if (direct) {
            s = s.charAt(s.length() - 1) + s.substring(0, s.length() - 1);
        } else {
            s = s.substring(1, s.length()) + s.charAt(0);
        }
        return s;
    }

    private String MoveWord(String s, boolean direct) {
        if (direct) {
            String[] arr = s.split(" ");
            s = arr[arr.length - 1];
            for (int i = 0; i < arr.length - 1; i++) {
                s += " " + arr[i];
            }
        } else {
            String[] arr = s.split(" ");
            s = "";
            for (int i = 1; i < arr.length; i++) {
                s += arr[i] + " ";
            }
            s += arr[0];
        }
        return s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput = new javax.swing.JTextField();
        btnStop = new javax.swing.JButton();
        lblDisplay = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxChar = new javax.swing.JRadioButton();
        cbxWord = new javax.swing.JRadioButton();
        cbxLeft = new javax.swing.JRadioButton();
        cbxRight = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        sldSpeed = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtInput.setText("Luu Viet Ha");

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblDisplay.setText("jLabel1");

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jLabel1.setText("Type:");

        jLabel2.setText("Side:");

        cbxChar.setText("Char");
        cbxChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCharActionPerformed(evt);
            }
        });

        cbxWord.setText("Word");
        cbxWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxWordActionPerformed(evt);
            }
        });

        cbxLeft.setText("Left");
        cbxLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLeftActionPerformed(evt);
            }
        });

        cbxRight.setText("Right");
        cbxRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRightActionPerformed(evt);
            }
        });

        jLabel3.setText("Result:");

        sldSpeed.setMajorTickSpacing(500);
        sldSpeed.setMaximum(2000);
        sldSpeed.setMinimum(100);
        sldSpeed.setMinorTickSpacing(100);
        sldSpeed.setPaintLabels(true);
        sldSpeed.setPaintTicks(true);
        sldSpeed.setValue(500);
        sldSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSpeedStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(18, 18, 18)
                        .addComponent(btnStop))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblDisplay))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtInput, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbxChar)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxWord))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbxLeft)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbxRight))))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(sldSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxChar)
                    .addComponent(cbxWord))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxLeft)
                    .addComponent(cbxRight))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnStop))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDisplay))
                .addGap(18, 18, 18)
                .addComponent(sldSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        CanRun = false;
        btnStart.setEnabled(true);
        btnStop.setEnabled(false);
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        s = txtInput.getText();
        CanRun = true;
        btnStart.setEnabled(false);
        btnStop.setEnabled(true);
    }//GEN-LAST:event_btnStartActionPerformed

    private void cbxCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCharActionPerformed
        if (cbxChar.isSelected())
            cbxWord.setSelected(false);
    }//GEN-LAST:event_cbxCharActionPerformed

    private void cbxLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLeftActionPerformed
        if (cbxLeft.isSelected())
            cbxRight.setSelected(false);
    }//GEN-LAST:event_cbxLeftActionPerformed

    private void cbxWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxWordActionPerformed
        if (cbxWord.isSelected())
            cbxChar.setSelected(false);
    }//GEN-LAST:event_cbxWordActionPerformed

    private void cbxRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRightActionPerformed
        if (cbxRight.isSelected())
            cbxLeft.setSelected(false);
    }//GEN-LAST:event_cbxRightActionPerformed

    private void sldSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSpeedStateChanged

    }//GEN-LAST:event_sldSpeedStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JRadioButton cbxChar;
    private javax.swing.JRadioButton cbxLeft;
    private javax.swing.JRadioButton cbxRight;
    private javax.swing.JRadioButton cbxWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JSlider sldSpeed;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
