/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ex;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author PH
 */
public class Ex2 extends javax.swing.JFrame {

    /**
     * Creates new form Ex2
     */
    public Ex2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTf = new javax.swing.JTextField();
        genBt = new javax.swing.JButton();
        rollNumTf = new javax.swing.JTextField();
        titleLb = new javax.swing.JLabel();
        resultLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameTf.setForeground(new java.awt.Color(204, 204, 204));
        nameTf.setText("Your Full Name");
        nameTf.setToolTipText("Your full name in real life");
        nameTf.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        nameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTfFocusLost(evt);
            }
        });
        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });
        nameTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTfKeyTyped(evt);
            }
        });

        genBt.setText("Generate");
        genBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genBtActionPerformed(evt);
            }
        });

        rollNumTf.setForeground(new java.awt.Color(204, 204, 204));
        rollNumTf.setText("Your Roll Number");
        rollNumTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rollNumTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rollNumTfFocusLost(evt);
            }
        });

        titleLb.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLb.setText("Generate Email");

        resultLb.setText("Your Email: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(titleLb)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rollNumTf)
                    .addComponent(nameTf, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(genBt)
                        .addGap(34, 34, 34)
                        .addComponent(resultLb)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLb)
                .addGap(31, 31, 31)
                .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rollNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genBt)
                    .addComponent(resultLb))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        
    }//GEN-LAST:event_nameTfActionPerformed

    private void nameTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTfKeyTyped
        
    }//GEN-LAST:event_nameTfKeyTyped

    private void nameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTfFocusGained
        if(nameTf.getText().equals("Your Full Name")){
            nameTf.setText("");
            nameTf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_nameTfFocusGained

    private void nameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTfFocusLost
        if(nameTf.getText().equals("")){
            nameTf.setText("Your Full Name");
            nameTf.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_nameTfFocusLost

    private void rollNumTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rollNumTfFocusGained
        if(rollNumTf.getText().equals("Your Roll Number")){
            rollNumTf.setText("");
            rollNumTf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_rollNumTfFocusGained

    private void rollNumTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rollNumTfFocusLost
        if(rollNumTf.getText().equals("")){
            rollNumTf.setText("Your Roll Number");
            rollNumTf.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_rollNumTfFocusLost

    private void genBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genBtActionPerformed
        String fullName = nameTf.getText();
        String rollNum = rollNumTf.getText();
        
        if(fullName.equals("Your Full Name") || rollNum.equals("Your Roll Number")){
            JOptionPane.showConfirmDialog(rootPane, "Pleas input Your Full Name and Your Roll Number");
        }
        else{
            String []fullNameArr = fullName.split(" ");
            String email ="";
            email += fullNameArr[fullNameArr.length-1];
            for(int i = 0; i < fullNameArr.length-1; i++){
                email+= String.valueOf(fullNameArr[i].charAt(0));
            }
            email += rollNum;
            resultLb.setText("Your Email: " + email.toLowerCase()+"@fpt.edu.vn");
        }        
    }//GEN-LAST:event_genBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton genBt;
    private javax.swing.JTextField nameTf;
    private javax.swing.JLabel resultLb;
    private javax.swing.JTextField rollNumTf;
    private javax.swing.JLabel titleLb;
    // End of variables declaration//GEN-END:variables
}
