package FirstApp;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;

/**
 *
 * @author LTTH
 */
public class demoFont extends javax.swing.JFrame {

    /**
     * Creates new form demoFont1
     */
    public demoFont() {
        initComponents();
        LoadFontName();
        LoadFontStyle();
        LoadColor();
    }
    Color textC, BackColor;
    Font f;
    private void getDefault(){
        f=lblDisplay.getFont();
        textC = lblDisplay.getForeground();
        BackColor = lblDisplay.getBackground();
    }
    private void LoadFontName() {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] fontName = ge.getAvailableFontFamilyNames();
        cbxFontName.setModel(new DefaultComboBoxModel<String>(fontName));
    }

    private void LoadFontStyle() {
        String[] fontStyle = {"Regular", "Italic", "Bold", "Bold & Italic"};
        lstFontStyle.setModel(new DefaultComboBoxModel<String>(fontStyle));
    }
    Color []c = {Color.red,Color.blue,Color.GREEN,Color.YELLOW,Color.orange,Color.gray};
    private void LoadColor(){
        String []ColorName = {"Red", "Blue", "Green", "Yellow", "Orange", "Gray"};
        cbxChangeColor.setModel(new DefaultComboBoxModel<>(ColorName));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxFontName = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtFontSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFontStyle = new javax.swing.JList<>();
        lblDisplay = new javax.swing.JTextField();
        btnFormat = new javax.swing.JButton();
        sldFontSize = new javax.swing.JSlider();
        spnFontSize = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        chkChangeColor = new javax.swing.JCheckBox();
        cbxChangeColor = new javax.swing.JComboBox<>();
        btnDefault = new javax.swing.JButton();
        btnColorChooser = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FontName");

        cbxFontName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxFontName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFontNameActionPerformed(evt);
            }
        });

        jLabel2.setText("FontStyle");

        txtFontSize.setText("15");
        txtFontSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFontSizeActionPerformed(evt);
            }
        });

        jLabel3.setText("FontSize");

        lstFontStyle.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstFontStyle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstFontStyleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstFontStyle);

        lblDisplay.setText("Tran Nhu Nhong");
        lblDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDisplayActionPerformed(evt);
            }
        });

        btnFormat.setText("Format");
        btnFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormatActionPerformed(evt);
            }
        });

        sldFontSize.setMajorTickSpacing(10);
        sldFontSize.setMinorTickSpacing(1);
        sldFontSize.setPaintLabels(true);
        sldFontSize.setPaintTicks(true);
        sldFontSize.setToolTipText("");
        sldFontSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFontSizeStateChanged(evt);
            }
        });

        spnFontSize.setModel(new javax.swing.SpinnerNumberModel(10, 10, 80, 5));
        spnFontSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnFontSizeStateChanged(evt);
            }
        });
        spnFontSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spnFontSizeMouseClicked(evt);
            }
        });

        jLabel4.setText("Change Color");

        chkChangeColor.setText("Color/BackGroundColor");
        chkChangeColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkChangeColorActionPerformed(evt);
            }
        });

        cbxChangeColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDefault.setText("Default");
        btnDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefaultActionPerformed(evt);
            }
        });

        btnColorChooser.setText("Color Chooser");
        btnColorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorChooserActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Text Color");

        jRadioButton2.setText("Background Color");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnFormat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDefault)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(cbxFontName, 0, 125, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)
                                                .addComponent(spnFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(sldFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(cbxChangeColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkChangeColor))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxFontName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sldFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxChangeColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnColorChooser)
                            .addComponent(chkChangeColor))))
                .addGap(18, 18, 18)
                .addComponent(lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormat)
                    .addComponent(btnDefault))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Format() {
        String fontName = cbxFontName.getSelectedItem() + "";
        int fontStyle = lstFontStyle.getSelectedIndex();
        int fontSize = 0;
//        try{ // Dùng để bắt lỗi, phải vượt qua đc điều kiện đầu tiên là số nguyên
//            fontSize = Integer.parseInt(txtFontSize.getText());
//            fontSize = fontSize>50?50:fontSize;
//            fontSize = fontSize<10?10:fontSize;
//        } catch(Exception e){
//            fontSize =15;
//        }

        fontSize = sldFontSize.getValue();
        fontSize = Integer.parseInt(spnFontSize.getValue() + "");
        lblDisplay.setFont(new Font(fontName, fontStyle, fontSize));
        if(chkChangeColor.isSelected()){ // doi mau text
            lblDisplay.setForeground(c[cbxChangeColor.getSelectedIndex()]);
        }else{ // doi mau nen
            lblDisplay.setBackground(c[cbxChangeColor.getSelectedIndex()]);
        }
    }
    private void btnFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormatActionPerformed
        // TODO add your handling code here:
        Format();
    }//GEN-LAST:event_btnFormatActionPerformed

    private void cbxFontNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFontNameActionPerformed
        // TODO add your handling code here:
        Format();
    }//GEN-LAST:event_cbxFontNameActionPerformed

    private void lstFontStyleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstFontStyleMouseClicked
        // TODO add your handling code here:
    //    Format();
    }//GEN-LAST:event_lstFontStyleMouseClicked

    private void txtFontSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFontSizeActionPerformed
        // TODO add your handling code here:
        Format();
    }//GEN-LAST:event_txtFontSizeActionPerformed

    private void spnFontSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spnFontSizeMouseClicked
        // TODO add your handling code here:
        //    Format();
    }//GEN-LAST:event_spnFontSizeMouseClicked

    private void sldFontSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFontSizeStateChanged
        // TODO add your handling code here:
        Format();
        spnFontSize.setValue(Integer.parseInt(sldFontSize.getValue() + ""));
    }//GEN-LAST:event_sldFontSizeStateChanged

    private void spnFontSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnFontSizeStateChanged
        // TODO add your handling code here:
        Format();
//        sldFontSize.setValue(Integer.parseInt(spnFontSize.getValue() + ""));
    }//GEN-LAST:event_spnFontSizeStateChanged

    private void lblDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDisplayActionPerformed
        // TODO add your handling code here:
    //    Format();
    }//GEN-LAST:event_lblDisplayActionPerformed

    private void btnDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefaultActionPerformed
        // TODO add your handling code here:
        lblDisplay.setFont(f);
        lblDisplay.setForeground(textC);
        lblDisplay.setBackground(BackColor);
    }//GEN-LAST:event_btnDefaultActionPerformed

    private void btnColorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorChooserActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(null, "Moi ban lua chon mau", Color.YELLOW);
        if(chkChangeColor.isSelected()){
            lblDisplay.setForeground(color);
        }else{
            lblDisplay.setBackground(color);
        }
    }//GEN-LAST:event_btnColorChooserActionPerformed

    private void chkChangeColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkChangeColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkChangeColorActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demoFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demoFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demoFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demoFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demoFont().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColorChooser;
    private javax.swing.JButton btnDefault;
    private javax.swing.JButton btnFormat;
    private javax.swing.JComboBox<String> cbxChangeColor;
    private javax.swing.JComboBox<String> cbxFontName;
    private javax.swing.JCheckBox chkChangeColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblDisplay;
    private javax.swing.JList<String> lstFontStyle;
    private javax.swing.JSlider sldFontSize;
    private javax.swing.JSpinner spnFontSize;
    private javax.swing.JTextField txtFontSize;
    // End of variables declaration//GEN-END:variables
}
